/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * История движений почтовых отправлений
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class History implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          mailPackageId;
    private Integer       typeId;
    private String        typeName;
    private Integer       attributeId;
    private String        attributeName;
    private LocalDateTime operDate;

    public History() {}

    public History(History value) {
        this.id = value.id;
        this.mailPackageId = value.mailPackageId;
        this.typeId = value.typeId;
        this.typeName = value.typeName;
        this.attributeId = value.attributeId;
        this.attributeName = value.attributeName;
        this.operDate = value.operDate;
    }

    public History(
        Long          id,
        Long          mailPackageId,
        Integer       typeId,
        String        typeName,
        Integer       attributeId,
        String        attributeName,
        LocalDateTime operDate
    ) {
        this.id = id;
        this.mailPackageId = mailPackageId;
        this.typeId = typeId;
        this.typeName = typeName;
        this.attributeId = attributeId;
        this.attributeName = attributeName;
        this.operDate = operDate;
    }

    /**
     * Getter for <code>pochtabot.history.id</code>. Идентификатор записи
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>pochtabot.history.id</code>. Идентификатор записи
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>pochtabot.history.mail_package_id</code>. Идентификатор почтового отправления
     */
    public Long getMailPackageId() {
        return this.mailPackageId;
    }

    /**
     * Setter for <code>pochtabot.history.mail_package_id</code>. Идентификатор почтового отправления
     */
    public void setMailPackageId(Long mailPackageId) {
        this.mailPackageId = mailPackageId;
    }

    /**
     * Getter for <code>pochtabot.history.type_id</code>. Идентификатор состояния
     */
    public Integer getTypeId() {
        return this.typeId;
    }

    /**
     * Setter for <code>pochtabot.history.type_id</code>. Идентификатор состояния
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * Getter for <code>pochtabot.history.type_name</code>. Наименование состояния
     */
    public String getTypeName() {
        return this.typeName;
    }

    /**
     * Setter for <code>pochtabot.history.type_name</code>. Наименование состояния
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * Getter for <code>pochtabot.history.attribute_id</code>. Идентификатор атрибута состояния
     */
    public Integer getAttributeId() {
        return this.attributeId;
    }

    /**
     * Setter for <code>pochtabot.history.attribute_id</code>. Идентификатор атрибута состояния
     */
    public void setAttributeId(Integer attributeId) {
        this.attributeId = attributeId;
    }

    /**
     * Getter for <code>pochtabot.history.attribute_name</code>. Наименование атрибута состояния
     */
    public String getAttributeName() {
        return this.attributeName;
    }

    /**
     * Setter for <code>pochtabot.history.attribute_name</code>. Наименование атрибута состояния
     */
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    /**
     * Getter for <code>pochtabot.history.oper_date</code>. Дата изменения состояния
     */
    public LocalDateTime getOperDate() {
        return this.operDate;
    }

    /**
     * Setter for <code>pochtabot.history.oper_date</code>. Дата изменения состояния
     */
    public void setOperDate(LocalDateTime operDate) {
        this.operDate = operDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("History (");

        sb.append(id);
        sb.append(", ").append(mailPackageId);
        sb.append(", ").append(typeId);
        sb.append(", ").append(typeName);
        sb.append(", ").append(attributeId);
        sb.append(", ").append(attributeName);
        sb.append(", ").append(operDate);

        sb.append(")");
        return sb.toString();
    }
}
