/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * Почтовые отправления
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailPackage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private Long          userId;
    private String        code;
    private Boolean       isDead;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public MailPackage() {}

    public MailPackage(MailPackage value) {
        this.id = value.id;
        this.userId = value.userId;
        this.code = value.code;
        this.isDead = value.isDead;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public MailPackage(
        Long          id,
        Long          userId,
        String        code,
        Boolean       isDead,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.code = code;
        this.isDead = isDead;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>pochtabot.mail_package.id</code>. Идентификатор почтового отправления
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>pochtabot.mail_package.id</code>. Идентификатор почтового отправления
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>pochtabot.mail_package.user_id</code>. Идентификатор пользователя/владельца
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>pochtabot.mail_package.user_id</code>. Идентификатор пользователя/владельца
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>pochtabot.mail_package.code</code>. Идентификационный код почтового отправления
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>pochtabot.mail_package.code</code>. Идентификационный код почтового отправления
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>pochtabot.mail_package.is_dead</code>. Признак завершенного почтового отправления
     */
    public Boolean getIsDead() {
        return this.isDead;
    }

    /**
     * Setter for <code>pochtabot.mail_package.is_dead</code>. Признак завершенного почтового отправления
     */
    public void setIsDead(Boolean isDead) {
        this.isDead = isDead;
    }

    /**
     * Getter for <code>pochtabot.mail_package.created_at</code>. Дата создания почтового отправления
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>pochtabot.mail_package.created_at</code>. Дата создания почтового отправления
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>pochtabot.mail_package.updated_at</code>. Дата обновления почтового отправления
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>pochtabot.mail_package.updated_at</code>. Дата обновления почтового отправления
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MailPackage (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(code);
        sb.append(", ").append(isDead);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
