/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db.tables.pojos;


import java.io.Serializable;


/**
 * Зарегистрированные пользователи
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long    id;
    private Long    chatId;
    private String  lang;
    private Boolean isAdmin;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.chatId = value.chatId;
        this.lang = value.lang;
        this.isAdmin = value.isAdmin;
    }

    public User(
        Long    id,
        Long    chatId,
        String  lang,
        Boolean isAdmin
    ) {
        this.id = id;
        this.chatId = chatId;
        this.lang = lang;
        this.isAdmin = isAdmin;
    }

    /**
     * Getter for <code>pochtabot.user.id</code>. Идентификатор пользователя
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>pochtabot.user.id</code>. Идентификатор пользователя
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>pochtabot.user.chat_id</code>. Идентификатор чата пользователя
     */
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>pochtabot.user.chat_id</code>. Идентификатор чата пользователя
     */
    public void setChatId(Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>pochtabot.user.lang</code>.
     */
    public String getLang() {
        return this.lang;
    }

    /**
     * Setter for <code>pochtabot.user.lang</code>.
     */
    public void setLang(String lang) {
        this.lang = lang;
    }

    /**
     * Getter for <code>pochtabot.user.is_admin</code>. Признак привилегированности пользователя
     */
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    /**
     * Setter for <code>pochtabot.user.is_admin</code>. Признак привилегированности пользователя
     */
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(chatId);
        sb.append(", ").append(lang);
        sb.append(", ").append(isAdmin);

        sb.append(")");
        return sb.toString();
    }
}
