#!/bin/bash

set -e
set -u

echo 'POGNALI'

psql -v ON_ERROR_STOP=1 <<-EOSQL
CREATE USER $BOT_POSTGRES_USER WITH
    LOGIN
    SUPERUSER
    INHERIT
    CREATEDB
    CREATEROLE
    NOREPLICATION
    ENCRYPTED PASSWORD '$BOT_POSTGRES_PASSWORD';

CREATE DATABASE $BOT_POSTGRES_DB
    WITH
    OWNER = $BOT_POSTGRES_USER
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    TEMPLATE = template0;

\connect $BOT_POSTGRES_DB;

CREATE SCHEMA IF NOT EXISTS russianpost AUTHORIZATION $BOT_POSTGRES_USER;
CREATE SCHEMA IF NOT EXISTS liquibase AUTHORIZATION $BOT_POSTGRES_USER;

EOSQL

echo 'DONE'
