/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.bletenkov.pochtabot.db.tables.History;
import ru.bletenkov.pochtabot.db.tables.MailPackage;
import ru.bletenkov.pochtabot.db.tables.User;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pochtabot extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pochtabot</code>
     */
    public static final Pochtabot POCHTABOT = new Pochtabot();

    /**
     * История движений почтовых отправлений
     */
    public final History HISTORY = History.HISTORY;

    /**
     * Почтовые отправления
     */
    public final MailPackage MAIL_PACKAGE = MailPackage.MAIL_PACKAGE;

    /**
     * Зарегистрированные пользователи
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Pochtabot() {
        super("pochtabot", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.HISTORY_ID_SEQ,
            Sequences.MAIL_PACKAGE_ID_SEQ,
            Sequences.USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            History.HISTORY,
            MailPackage.MAIL_PACKAGE,
            User.USER);
    }
}
