/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in pochtabot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>pochtabot.history_id_seq</code>
     */
    public static final Sequence<Long> HISTORY_ID_SEQ = Internal.createSequence("history_id_seq", Pochtabot.POCHTABOT, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>pochtabot.mail_package_id_seq</code>
     */
    public static final Sequence<Long> MAIL_PACKAGE_ID_SEQ = Internal.createSequence("mail_package_id_seq", Pochtabot.POCHTABOT, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>pochtabot.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = Internal.createSequence("user_id_seq", Pochtabot.POCHTABOT, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
