/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db;


import ru.bletenkov.pochtabot.db.tables.History;
import ru.bletenkov.pochtabot.db.tables.MailPackage;
import ru.bletenkov.pochtabot.db.tables.User;


/**
 * Convenience access to all tables in pochtabot.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * История движений почтовых отправлений
     */
    public static final History HISTORY = History.HISTORY;

    /**
     * Почтовые отправления
     */
    public static final MailPackage MAIL_PACKAGE = MailPackage.MAIL_PACKAGE;

    /**
     * Зарегистрированные пользователи
     */
    public static final User USER = User.USER;
}
