/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import ru.bletenkov.pochtabot.db.tables.History;


/**
 * История движений почтовых отправлений
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HistoryRecord extends UpdatableRecordImpl<HistoryRecord> implements Record7<Long, Long, Integer, String, Integer, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pochtabot.history.id</code>. Идентификатор записи
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pochtabot.history.id</code>. Идентификатор записи
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pochtabot.history.mail_package_id</code>. Идентификатор почтового отправления
     */
    public void setMailPackageId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pochtabot.history.mail_package_id</code>. Идентификатор почтового отправления
     */
    public Long getMailPackageId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pochtabot.history.type_id</code>. Идентификатор состояния
     */
    public void setTypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>pochtabot.history.type_id</code>. Идентификатор состояния
     */
    public Integer getTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>pochtabot.history.type_name</code>. Наименование состояния
     */
    public void setTypeName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>pochtabot.history.type_name</code>. Наименование состояния
     */
    public String getTypeName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>pochtabot.history.attribute_id</code>. Идентификатор атрибута состояния
     */
    public void setAttributeId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>pochtabot.history.attribute_id</code>. Идентификатор атрибута состояния
     */
    public Integer getAttributeId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>pochtabot.history.attribute_name</code>. Наименование атрибута состояния
     */
    public void setAttributeName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>pochtabot.history.attribute_name</code>. Наименование атрибута состояния
     */
    public String getAttributeName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>pochtabot.history.oper_date</code>. Дата изменения состояния
     */
    public void setOperDate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>pochtabot.history.oper_date</code>. Дата изменения состояния
     */
    public LocalDateTime getOperDate() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Integer, String, Integer, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Integer, String, Integer, String, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return History.HISTORY.ID;
    }

    @Override
    public Field<Long> field2() {
        return History.HISTORY.MAIL_PACKAGE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return History.HISTORY.TYPE_ID;
    }

    @Override
    public Field<String> field4() {
        return History.HISTORY.TYPE_NAME;
    }

    @Override
    public Field<Integer> field5() {
        return History.HISTORY.ATTRIBUTE_ID;
    }

    @Override
    public Field<String> field6() {
        return History.HISTORY.ATTRIBUTE_NAME;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return History.HISTORY.OPER_DATE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getMailPackageId();
    }

    @Override
    public Integer component3() {
        return getTypeId();
    }

    @Override
    public String component4() {
        return getTypeName();
    }

    @Override
    public Integer component5() {
        return getAttributeId();
    }

    @Override
    public String component6() {
        return getAttributeName();
    }

    @Override
    public LocalDateTime component7() {
        return getOperDate();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getMailPackageId();
    }

    @Override
    public Integer value3() {
        return getTypeId();
    }

    @Override
    public String value4() {
        return getTypeName();
    }

    @Override
    public Integer value5() {
        return getAttributeId();
    }

    @Override
    public String value6() {
        return getAttributeName();
    }

    @Override
    public LocalDateTime value7() {
        return getOperDate();
    }

    @Override
    public HistoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public HistoryRecord value2(Long value) {
        setMailPackageId(value);
        return this;
    }

    @Override
    public HistoryRecord value3(Integer value) {
        setTypeId(value);
        return this;
    }

    @Override
    public HistoryRecord value4(String value) {
        setTypeName(value);
        return this;
    }

    @Override
    public HistoryRecord value5(Integer value) {
        setAttributeId(value);
        return this;
    }

    @Override
    public HistoryRecord value6(String value) {
        setAttributeName(value);
        return this;
    }

    @Override
    public HistoryRecord value7(LocalDateTime value) {
        setOperDate(value);
        return this;
    }

    @Override
    public HistoryRecord values(Long value1, Long value2, Integer value3, String value4, Integer value5, String value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HistoryRecord
     */
    public HistoryRecord() {
        super(History.HISTORY);
    }

    /**
     * Create a detached, initialised HistoryRecord
     */
    public HistoryRecord(Long id, Long mailPackageId, Integer typeId, String typeName, Integer attributeId, String attributeName, LocalDateTime operDate) {
        super(History.HISTORY);

        setId(id);
        setMailPackageId(mailPackageId);
        setTypeId(typeId);
        setTypeName(typeName);
        setAttributeId(attributeId);
        setAttributeName(attributeName);
        setOperDate(operDate);
    }
}
