/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.bletenkov.pochtabot.db.tables.MailPackage;


/**
 * Почтовые отправления
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailPackageRecord extends UpdatableRecordImpl<MailPackageRecord> implements Record6<Long, Long, String, Boolean, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pochtabot.mail_package.id</code>. Идентификатор почтового отправления
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pochtabot.mail_package.id</code>. Идентификатор почтового отправления
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pochtabot.mail_package.user_id</code>. Идентификатор пользователя/владельца
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>pochtabot.mail_package.user_id</code>. Идентификатор пользователя/владельца
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>pochtabot.mail_package.code</code>. Идентификационный код почтового отправления
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>pochtabot.mail_package.code</code>. Идентификационный код почтового отправления
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>pochtabot.mail_package.is_dead</code>. Признак завершенного почтового отправления
     */
    public void setIsDead(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>pochtabot.mail_package.is_dead</code>. Признак завершенного почтового отправления
     */
    public Boolean getIsDead() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>pochtabot.mail_package.created_at</code>. Дата создания почтового отправления
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>pochtabot.mail_package.created_at</code>. Дата создания почтового отправления
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>pochtabot.mail_package.updated_at</code>. Дата обновления почтового отправления
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>pochtabot.mail_package.updated_at</code>. Дата обновления почтового отправления
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, Boolean, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, Boolean, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MailPackage.MAIL_PACKAGE.ID;
    }

    @Override
    public Field<Long> field2() {
        return MailPackage.MAIL_PACKAGE.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return MailPackage.MAIL_PACKAGE.CODE;
    }

    @Override
    public Field<Boolean> field4() {
        return MailPackage.MAIL_PACKAGE.IS_DEAD;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return MailPackage.MAIL_PACKAGE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return MailPackage.MAIL_PACKAGE.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getCode();
    }

    @Override
    public Boolean component4() {
        return getIsDead();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getCode();
    }

    @Override
    public Boolean value4() {
        return getIsDead();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public MailPackageRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MailPackageRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public MailPackageRecord value3(String value) {
        setCode(value);
        return this;
    }

    @Override
    public MailPackageRecord value4(Boolean value) {
        setIsDead(value);
        return this;
    }

    @Override
    public MailPackageRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public MailPackageRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public MailPackageRecord values(Long value1, Long value2, String value3, Boolean value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MailPackageRecord
     */
    public MailPackageRecord() {
        super(MailPackage.MAIL_PACKAGE);
    }

    /**
     * Create a detached, initialised MailPackageRecord
     */
    public MailPackageRecord(Long id, Long userId, String code, Boolean isDead, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(MailPackage.MAIL_PACKAGE);

        setId(id);
        setUserId(userId);
        setCode(code);
        setIsDead(isDead);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
