/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ru.bletenkov.pochtabot.db.tables.History;
import ru.bletenkov.pochtabot.db.tables.records.HistoryRecord;


/**
 * История движений почтовых отправлений
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HistoryDao extends DAOImpl<HistoryRecord, ru.bletenkov.pochtabot.db.tables.pojos.History, Long> {

    /**
     * Create a new HistoryDao without any configuration
     */
    public HistoryDao() {
        super(History.HISTORY, ru.bletenkov.pochtabot.db.tables.pojos.History.class);
    }

    /**
     * Create a new HistoryDao with an attached configuration
     */
    public HistoryDao(Configuration configuration) {
        super(History.HISTORY, ru.bletenkov.pochtabot.db.tables.pojos.History.class, configuration);
    }

    @Override
    public Long getId(ru.bletenkov.pochtabot.db.tables.pojos.History object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(History.HISTORY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchById(Long... values) {
        return fetch(History.HISTORY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ru.bletenkov.pochtabot.db.tables.pojos.History fetchOneById(Long value) {
        return fetchOne(History.HISTORY.ID, value);
    }

    /**
     * Fetch records that have <code>mail_package_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchRangeOfMailPackageId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(History.HISTORY.MAIL_PACKAGE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mail_package_id IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchByMailPackageId(Long... values) {
        return fetch(History.HISTORY.MAIL_PACKAGE_ID, values);
    }

    /**
     * Fetch records that have <code>type_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchRangeOfTypeId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(History.HISTORY.TYPE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type_id IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchByTypeId(Integer... values) {
        return fetch(History.HISTORY.TYPE_ID, values);
    }

    /**
     * Fetch records that have <code>type_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchRangeOfTypeName(String lowerInclusive, String upperInclusive) {
        return fetchRange(History.HISTORY.TYPE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type_name IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchByTypeName(String... values) {
        return fetch(History.HISTORY.TYPE_NAME, values);
    }

    /**
     * Fetch records that have <code>attribute_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchRangeOfAttributeId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(History.HISTORY.ATTRIBUTE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attribute_id IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchByAttributeId(Integer... values) {
        return fetch(History.HISTORY.ATTRIBUTE_ID, values);
    }

    /**
     * Fetch records that have <code>attribute_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchRangeOfAttributeName(String lowerInclusive, String upperInclusive) {
        return fetchRange(History.HISTORY.ATTRIBUTE_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>attribute_name IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchByAttributeName(String... values) {
        return fetch(History.HISTORY.ATTRIBUTE_NAME, values);
    }

    /**
     * Fetch records that have <code>oper_date BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchRangeOfOperDate(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(History.HISTORY.OPER_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>oper_date IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.History> fetchByOperDate(LocalDateTime... values) {
        return fetch(History.HISTORY.OPER_DATE, values);
    }
}
