/*
 * This file is generated by jOOQ.
 */
package ru.bletenkov.pochtabot.db.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import ru.bletenkov.pochtabot.db.tables.MailPackage;
import ru.bletenkov.pochtabot.db.tables.records.MailPackageRecord;


/**
 * Почтовые отправления
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MailPackageDao extends DAOImpl<MailPackageRecord, ru.bletenkov.pochtabot.db.tables.pojos.MailPackage, Long> {

    /**
     * Create a new MailPackageDao without any configuration
     */
    public MailPackageDao() {
        super(MailPackage.MAIL_PACKAGE, ru.bletenkov.pochtabot.db.tables.pojos.MailPackage.class);
    }

    /**
     * Create a new MailPackageDao with an attached configuration
     */
    public MailPackageDao(Configuration configuration) {
        super(MailPackage.MAIL_PACKAGE, ru.bletenkov.pochtabot.db.tables.pojos.MailPackage.class, configuration);
    }

    @Override
    public Long getId(ru.bletenkov.pochtabot.db.tables.pojos.MailPackage object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MailPackage.MAIL_PACKAGE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchById(Long... values) {
        return fetch(MailPackage.MAIL_PACKAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ru.bletenkov.pochtabot.db.tables.pojos.MailPackage fetchOneById(Long value) {
        return fetchOne(MailPackage.MAIL_PACKAGE.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MailPackage.MAIL_PACKAGE.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchByUserId(Long... values) {
        return fetch(MailPackage.MAIL_PACKAGE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchRangeOfCode(String lowerInclusive, String upperInclusive) {
        return fetchRange(MailPackage.MAIL_PACKAGE.CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchByCode(String... values) {
        return fetch(MailPackage.MAIL_PACKAGE.CODE, values);
    }

    /**
     * Fetch records that have <code>is_dead BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchRangeOfIsDead(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(MailPackage.MAIL_PACKAGE.IS_DEAD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_dead IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchByIsDead(Boolean... values) {
        return fetch(MailPackage.MAIL_PACKAGE.IS_DEAD, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MailPackage.MAIL_PACKAGE.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(MailPackage.MAIL_PACKAGE.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MailPackage.MAIL_PACKAGE.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<ru.bletenkov.pochtabot.db.tables.pojos.MailPackage> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(MailPackage.MAIL_PACKAGE.UPDATED_AT, values);
    }
}
